prompt RESET IDENTITY COLUMNS

prompt - table co_products
alter table co_products modify product_id 
  generated by default on null as identity (start with limit value);

prompt - table co_stores
alter table co_stores modify store_id 
  generated by default on null as identity (start with limit value);
  
prompt - table co_customers
alter table co_customers modify customer_id 
  generated by default on null as identity (start with limit value);

prompt - table co_orders
alter table co_orders modify order_id 
  generated by default on null as identity (start with limit value);