-- Script generated by PLEX version 2.4.0 - more infos here: https://github.com/ogobrecht/plex
-- Performance Hacks by Connor McDonald: https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
-- For strange line end replacements a big thank to SQL*Plus: https://support.oracle.com/epmos/faces/DocumentDisplay?id=2377701.1 (SQL Failed With ORA-1756 In Sqlplus But Works In SQL Developer)
prompt - insert     16 rows into DRS_CATEGORY
set define off feedback off sqlblanklines on
alter session set cursor_sharing = force;
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';
alter session set nls_timestamp_format = 'yyyy-mm-dd hh24:mi:ssxff';
alter session set nls_timestamp_tz_format = 'yyyy-mm-dd hh24:mi:ssxff tzr';
begin
insert all
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (1,'Action','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (2,'Animation','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (3,'Children','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (4,'Classics','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (5,'Comedy','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (6,'Documentary','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (7,'Drama','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (8,'Family','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (9,'Foreign','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (10,'Games','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (11,'Horror','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (12,'Music','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (13,'New','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (14,'Sci-Fi','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (15,'Sports','2006-02-15 04:46:27')
into DRS_CATEGORY(CATEGORY_ID,NAME,LAST_UPDATE) values (16,'Travel','2006-02-15 04:46:27')
select * from dual;
end;
/
commit;
alter session set cursor_sharing = exact;

