-- Script generated by PLEX version 2.4.0 - more infos here: https://github.com/ogobrecht/plex
-- Performance Hacks by Connor McDonald: https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
-- For strange line end replacements a big thank to SQL*Plus: https://support.oracle.com/epmos/faces/DocumentDisplay?id=2377701.1 (SQL Failed With ORA-1756 In Sqlplus But Works In SQL Developer)
prompt - insert      2 rows into DRS_STAFF
set define off feedback off sqlblanklines on
alter session set cursor_sharing = force;
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';
alter session set nls_timestamp_format = 'yyyy-mm-dd hh24:mi:ssxff';
alter session set nls_timestamp_tz_format = 'yyyy-mm-dd hh24:mi:ssxff tzr';
begin
insert all
into DRS_STAFF(STAFF_ID,FIRST_NAME,LAST_NAME,ADDRESS_ID,PICTURE,EMAIL,STORE_ID,ACTIVE,USERNAME,PASSWORD,LAST_UPDATE) values (1,'Mike','Hillyer',3,NULL,'Mike.Hillyer@sakilastaff.com',1,1,'Mike','8cb2237d0679ca88db6464eac60da96345513964','2006-02-15 04:57:16')
into DRS_STAFF(STAFF_ID,FIRST_NAME,LAST_NAME,ADDRESS_ID,PICTURE,EMAIL,STORE_ID,ACTIVE,USERNAME,PASSWORD,LAST_UPDATE) values (2,'Jon','Stephens',4,NULL,'Jon.Stephens@sakilastaff.com',2,1,'Jon','8cb2237d0679ca88db6464eac60da96345513964','2006-02-15 04:57:16')
select * from dual;
end;
/
commit;
alter session set cursor_sharing = exact;

