prompt - table oehr_promotions

create table oehr_promotions (
  promo_id   integer           generated by default on null as identity (increment by 10 nocache nocycle),
  promo_name varchar2(20 char) ,
  --
  primary key (promo_id)
) ;
