prompt - table oehr_locations

create table oehr_locations (
  location_id    integer           generated by default on null as identity (increment by 100 nocache nocycle),
  street_address varchar2(40 char) ,
  postal_code    varchar2(12 char) ,
  city           varchar2(30 char) not null,
  state_province varchar2(25 char) ,
  country_id     char(2 byte)      ,
  --
  primary key (location_id)
);

comment on table oehr_locations is
  'Locations table that contains specific address of a specific office, warehouse, and/or production site of a company. Does not store addresses / locations of customers. Contains 23 rows; references with the departments and countries tables.';

comment on column oehr_locations.location_id is
  'Primary key of locations table.';

comment on column oehr_locations.street_address is
  'Street address of an office, warehouse, or production site of a company. Contains building number and street name.';

comment on column oehr_locations.postal_code is
  'Postal code of the location of an office, warehouse, or production site of a company.';

comment on column oehr_locations.city is
  'A not null column that shows city where an office, warehouse, or production site of a company is located.';

comment on column oehr_locations.state_province is
  'State or Province where an office, warehouse, or production site of a company is located.';

comment on column oehr_locations.country_id is
  'Country where an office, warehouse, or production site of a company is located. Foreign key to country_id column of the countries table.';
