prompt - table hr_departments

create table hr_departments (
  department_id   number(4) generated by default on null as identity (start with 280 increment by 10 maxvalue 9990 nocache nocycle) primary key,
  department_name varchar2(30) not null,
  manager_id      number(6),
  location_id     number(4) references locations
);

comment on table hr_departments is
  'Departments table that shows details of departments where employees work. Contains 27 rows; references with locations, employees, and job_history tables.';

comment on column hr_departments.department_id is
  'Primary key column of departments table.';

comment on column hr_departments.department_name is
  'A not null column that shows name of a department. Administration, Marketing, Purchasing, Human Resources, Shipping, IT, Executive, Public Relations, Sales, Finance, and Accounting. ';

comment on column hr_departments.manager_id is
  'Manager_id of a department. Foreign key to employee_id column of employees table. The manager_id column of the employee table references this column.';

comment on column hr_departments.location_id is
  'Location id where a department is located. Foreign key to location_id column of locations table.';