prompt - table hr_locations

create table hr_locations (
  location_id    number(4)    generated by default on null as identity (start with 3300 increment by 100 maxvalue 9900 nocache nocycle),
  street_address varchar2(40) ,
  postal_code    varchar2(12) ,
  city           varchar2(30) not null,
  state_province varchar2(25) ,
  country_id     char(2)      ,
  --
  primary key (location_id)
);

comment on table hr_locations is
  'Locations table that contains specific address of a specific office, warehouse, and/or production site of a company. Does not store addresses / locations of customers. Contains 23 rows; references with the departments and countries tables.';

comment on column hr_locations.location_id is
  'Primary key of locations table.';

comment on column hr_locations.street_address is
  'Street address of an office, warehouse, or production site of a company. Contains building number and street name.';

comment on column hr_locations.postal_code is
  'Postal code of the location of an office, warehouse, or production site of a company.';

comment on column hr_locations.city is
  'A not null column that shows city where an office, warehouse, or production site of a company is located.';

comment on column hr_locations.state_province is
  'State or Province where an office, warehouse, or production site of a company is located.';

comment on column hr_locations.country_id is
  'Country where an office, warehouse, or production site of a company is located. Foreign key to country_id column of the countries table.';
