prompt RESET IDENTITY COLUMNS

prompt - table oehr_departments
alter table oehr_departments modify department_id
  generated by default on null as identity (start with limit value increment by 10 maxvalue 9990 nocache nocycle)

prompt - table oehr_employees
alter table oehr_employees modify employee_id
  generated by default on null as identity (start with limit value increment by 1 nocache nocycle);

prompt - table oehr_locations
alter table oehr_locations modify location_id
  generated by default on null as identity (start with limit value increment by 100 maxvalue 9900 nocache nocycle);

prompt - table oehr_regions
alter table oehr_regions modify region_id
  generated by default on null as identity (start with limit value);