prompt RESET IDENTITY COLUMNS

prompt - table oehr_departments
alter table oehr_departments modify department_id
  generated by default on null as identity (start with limit value)

prompt - table oehr_employees
alter table oehr_employees modify employee_id
  generated by default on null as identity (start with limit value);

prompt - table oehr_locations
alter table oehr_locations modify location_id
  generated by default on null as identity (start with limit value);

prompt - table oehr_regions
alter table oehr_regions modify region_id
  generated by default on null as identity (start with limit value);