prompt - table ed_dept

create table ed_dept (
  deptno number(2,0)       generated by default on null as identity (start with 50 increment by 10 maxvalue 9000 nocache nocycle),
  dname  varchar2(50 char) ,
  loc    varchar2(50 char) ,
  --
  primary key (deptno)
);

