prompt - table ed_emp

create table ed_emp (
  empno    number(4,0)       generated by default on null as identity (start with 8000 increment by 10 maxvalue 90000 nocache nocycle),
	ename    varchar2(50 char) ,
	job      varchar2(50 char) ,
	mgr      number(4,0)       ,
	hiredate date              ,
	sal      number(7,2)       ,
	comm     number(7,2)       ,
	deptno   number(2,0)       ,
  --
  primary key (empno)
);

