-- Script generated by PLEX version 2.4.0 - more infos here: https://github.com/ogobrecht/plex
-- Performance Hacks by Connor McDonald: https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
-- For strange line end replacements a big thank to SQL*Plus: https://support.oracle.com/epmos/faces/DocumentDisplay?id=2377701.1 (SQL Failed With ORA-1756 In Sqlplus But Works In SQL Developer)
prompt - insert    9 rows into OEHR_WAREHOUSES
set define off feedback off sqlblanklines on
alter session set cursor_sharing = force;
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';
alter session set nls_timestamp_format = 'yyyy-mm-dd hh24:mi:ssxff';
alter session set nls_timestamp_tz_format = 'yyyy-mm-dd hh24:mi:ssxff tzr';
begin
insert all
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (1,'Southlake, Texas',1400)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (2,'San Francisco',1500)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (3,'New Jersey',1600)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (4,'Seattle, Washington',1700)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (5,'Toronto',1800)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (6,'Sydney',2200)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (7,'Mexico City',3200)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (8,'Beijing',2000)
into OEHR_WAREHOUSES(WAREHOUSE_ID,WAREHOUSE_NAME,LOCATION_ID) values (9,'Bombay',2100)
select * from dual;
end;
/
commit;
alter session set cursor_sharing = exact;

