-- Script generated by PLEX version 2.4.0 - more infos here: https://github.com/ogobrecht/plex
-- Performance Hacks by Connor McDonald: https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
-- For strange line end replacements a big thank to SQL*Plus: https://support.oracle.com/epmos/faces/DocumentDisplay?id=2377701.1 (SQL Failed With ORA-1756 In Sqlplus But Works In SQL Developer)
prompt - insert   10 rows into OEHR_JOB_HISTORY
set define off feedback off sqlblanklines on
alter session set cursor_sharing = force;
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';
alter session set nls_timestamp_format = 'yyyy-mm-dd hh24:mi:ssxff';
alter session set nls_timestamp_tz_format = 'yyyy-mm-dd hh24:mi:ssxff tzr';
begin
insert all
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (101,'2009-04-06 00:00:00','2013-05-12 00:00:00','AC_ACCOUNT',110)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (101,'2013-05-13 00:00:00','2016-09-28 00:00:00','AC_MGR',110)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (102,'2012-07-29 00:00:00','2018-02-06 00:00:00','IT_PROG',60)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (114,'2017-10-07 00:00:00','2019-07-16 00:00:00','ST_CLERK',50)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (122,'2018-07-17 00:00:00','2019-07-16 00:00:00','ST_CLERK',50)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (176,'2017-10-07 00:00:00','2018-07-16 00:00:00','SA_REP',80)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (176,'2018-07-17 00:00:00','2019-07-16 00:00:00','SA_MAN',80)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (200,'2007-04-02 00:00:00','2012-12-31 00:00:00','AD_ASST',90)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (200,'2014-01-14 00:00:00','2018-07-16 00:00:00','AC_ACCOUNT',90)
into OEHR_JOB_HISTORY(EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (201,'2015-09-02 00:00:00','2019-07-04 00:00:00','MK_REP',20)
select * from dual;
end;
/
commit;
alter session set cursor_sharing = exact;

