-- Script generated by PLEX version 2.4.0 - more infos here: https://github.com/ogobrecht/plex
-- Performance Hacks by Connor McDonald: https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
-- For strange line end replacements a big thank to SQL*Plus: https://support.oracle.com/epmos/faces/DocumentDisplay?id=2377701.1 (SQL Failed With ORA-1756 In Sqlplus But Works In SQL Developer)
prompt - insert    4 rows into OEHR_REGIONS
set define off feedback off sqlblanklines on
alter session set cursor_sharing = force;
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';
alter session set nls_timestamp_format = 'yyyy-mm-dd hh24:mi:ssxff';
alter session set nls_timestamp_tz_format = 'yyyy-mm-dd hh24:mi:ssxff tzr';
begin
insert all
into OEHR_REGIONS(REGION_ID,REGION_NAME) values (1,'Europe')
into OEHR_REGIONS(REGION_ID,REGION_NAME) values (2,'Americas')
into OEHR_REGIONS(REGION_ID,REGION_NAME) values (3,'Asia')
into OEHR_REGIONS(REGION_ID,REGION_NAME) values (4,'Middle East and Africa')
select * from dual;
end;
/
commit;
alter session set cursor_sharing = exact;

