-- Script generated by PLEX version 2.4.0 - more infos here: https://github.com/ogobrecht/plex
-- Performance Hacks by Connor McDonald: https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
-- For strange line end replacements a big thank to SQL*Plus: https://support.oracle.com/epmos/faces/DocumentDisplay?id=2377701.1 (SQL Failed With ORA-1756 In Sqlplus But Works In SQL Developer)
prompt - insert   25 rows into OEHR_COUNTRIES
set define off feedback off sqlblanklines on
alter session set cursor_sharing = force;
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss';
alter session set nls_timestamp_format = 'yyyy-mm-dd hh24:mi:ssxff';
alter session set nls_timestamp_tz_format = 'yyyy-mm-dd hh24:mi:ssxff tzr';
begin
insert all
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('AR','Argentina',2)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('AU','Australia',3)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('BE','Belgium',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('BR','Brazil',2)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('CA','Canada',2)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('CH','Switzerland',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('CN','China',3)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('DE','Germany',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('DK','Denmark',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('EG','Egypt',4)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('FR','France',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('HK','HongKong',3)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('IL','Israel',4)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('IN','India',3)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('IT','Italy',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('JP','Japan',3)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('KW','Kuwait',4)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('MX','Mexico',2)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('NG','Nigeria',4)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('NL','Netherlands',1)
select * from dual;
insert all
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('SG','Singapore',3)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('UK','United Kingdom',1)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('US','United States of America',2)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('ZM','Zambia',4)
into OEHR_COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) values ('ZW','Zimbabwe',4)
select * from dual;
end;
/
commit;
alter session set cursor_sharing = exact;

