prompt - table co_customers

create table co_customers (
  customer_id   integer generated by default on null as identity primary key,
  email_address varchar2(255 char) not null unique,
  full_name     varchar2(255 char) not null
);

comment on table co_customers is
  'Details of the people placing orders';

comment on column co_customers.customer_id is
  'Auto-incrementing primary key';

comment on column co_customers.email_address is
  'The email address the person uses to access the account';

comment on column co_customers.full_name is
  'What this customer is called';