prompt - table co_inventory

create table co_inventory (
  inventory_id      integer generated by default on null as identity,
  store_id          integer not null ,
  product_id        integer not null ,
  product_inventory integer not null ,
  --
  primary key (inventory_id),
  unique      (store_id, product_id)
);

comment on table co_inventory is
  'Details of the quantity of stock available for products at each location';

comment on column co_inventory.inventory_id is
  'Auto-incrementing primary key';

comment on column co_inventory.store_id is
  'Which location the goods are located at';

comment on column co_inventory.product_id is
  'Which item this stock is for';

comment on column co_inventory.product_inventory is
  'The current quantity in stock';
