prompt - table co_shipments

create table co_shipments (
  shipment_id      integer            generated by default on null as identity,
  store_id         integer            not null ,
  customer_id      integer            not null ,
  delivery_address varchar2(512 char) not null ,
  shipment_status  varchar2(100 char) not null ,
  --
  primary key (shipment_id),
  check (shipment_status in ('CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'))
);

comment on table co_shipments is
  'Details of where ordered goods will be delivered';

comment on column co_shipments.shipment_id is
  'Auto-incrementing primary key';

comment on column co_shipments.store_id is
  'Which location the goods will be transported from';

comment on column co_shipments.customer_id is
  'Who this shipment is for';

comment on column co_shipments.delivery_address is
  'Where the goods will be transported to';

comment on column co_shipments.shipment_status is
  'The current status of the shipment. Valid values are:
CREATED - the shipment is ready for order assignment
SHIPPED - the goods have been dispatched
IN-TRANSIT - the goods are en-route to their destination
DELIVERED - the good have arrived at their destination';