prompt - table drs_actor

create table drs_actor (
  actor_id    integer     generated by default on null as identity,
  first_name  varchar(45) not null,
  last_name   varchar(45) not null,
  last_update date        not null,
  --
  primary key (actor_id)
);

