prompt - table drs_staff

create table drs_staff (
  staff_id    integer           generated by default on null as identity,
  first_name  varchar2(45 char)              not null ,
  last_name   varchar2(45 char)              not null ,
  address_id  integer                        not null ,
  picture     blob              default null          ,
  email       varchar2(50 char) default null          ,
  store_id    integer                        not null ,
  active      number(1,0)       default 1    not null ,
  username    varchar2(16 char)              not null ,
  password    varchar2(40 char) default null          ,
  last_update date                           not null ,
  --
  primary key (staff_id),
  check       (active in (0,1))
);

