prompt - table drs_language

create table drs_language (
  language_id integer           generated by default on null as identity,
  name        varchar2(20 char) not null ,
  last_update date              not null ,
  --
  primary key (language_id)
);
