prompt - table drs_film

create table drs_film (
  film_id              integer       generated by default on null as identity,
  title                varchar2(255)               not null ,
  description          clob          default null           ,
  release_year         varchar2(4)   default null           ,
  language_id          integer                     not null ,
  original_language_id integer       default null           ,
  drs_rental_duration  integer       default 3     not null ,
  drs_rental_rate      number(4,2)   default 4.99  not null ,
  length               integer       default null           ,
  replacement_cost     number(5,2)   default 19.99 not null ,
  rating               varchar2(10)  default 'g'            ,
  special_features     varchar2(100) default null           ,
  last_update          date                        not null ,
  --
  primary key (film_id),
  check       (rating in ('g','pg','pg-13','r','nc-17')),
  check       (special_features is null or
               special_features like '%trailers%' or
               special_features like '%commentaries%' or
               special_features like '%deleted scenes%' or
               special_features like '%behind the scenes%')
);
