prompt - table drs_city

create table drs_city (
  city_id     integer     generated by default on null as identity,
  city        varchar(50) not null,
  country_id  integer     not null,
  last_update date        not null,
  --
  primary key (city_id)
);
