prompt - table drs_store

create table drs_store (
  store_id         integer generated by default on null as identity,
  manager_staff_id integer not null ,
  address_id       integer not null ,
  last_update      date    not null ,
  --
  primary key (store_id)
);
