prompt - table drs_customer

create table drs_customer (
  customer_id integer           generated by default on null as identity,
  store_id    integer                        not null ,
  first_name  varchar2(45 char)              not null ,
  last_name   varchar2(45 char)              not null ,
  email       varchar2(50 char) default null          ,
  address_id  integer                        not null ,
  active      number(1,0)       default 1    not null ,
  create_date date                           not null ,
  last_update date                           not null ,
  --
  primary key  (customer_id),
  check        (active in (0,1))
);
