prompt - table drs_film_text

create table drs_film_text (
  film_id     integer            generated by default on null as identity,
  title       varchar2(255 char) not null ,
  description clob                        ,
  --
  primary key (film_id)
);
