prompt - table drs_address

create table drs_address (
  address_id  integer           generated by default on null as identity,
  address     varchar2(50 char)              not null ,
  address2    varchar2(50 char) default null          ,
  district    varchar2(20 char)              not null ,
  city_id     integer                        not null ,
  postal_code varchar2(10 char) default null          ,
  phone       varchar2(20 char)              not null ,
  last_update date                           not null ,
  --
  primary key (address_id)
);