prompt - table drs_film

create table drs_film (
  film_id              integer            generated by default on null as identity,
  title                varchar2(255 char)               not null ,
  description          clob               default null           ,
  release_year         varchar2(4 char)   default null           ,
  language_id          integer                          not null ,
  original_language_id integer            default null           ,
  rental_duration      integer            default 3     not null ,
  rental_rate          number(4,2)        default 4.99  not null ,
  length               integer            default null           ,
  replacement_cost     number(5,2)        default 19.99 not null ,
  rating               varchar2(10 char)  default 'g'            ,
  special_features     varchar2(100 char) default null           ,
  last_update          date                             not null ,
  --
  primary key (film_id),
  check       (rating in ('G','PG','PG-13','R','NC-17')),
  check       (special_features is null or
               special_features like '%Trailers%' or
               special_features like '%Commentaries%' or
               special_features like '%Deleted Scenes%' or
               special_features like '%Behind the Scenes%')
);
