prompt - table drs_country

create table drs_country (
  country_id  integer      generated by default on null as identity,
  country     varchar2(50) not null,
  last_update date         ,
  --
  primary key (country_id)
);
