prompt - table drs_address

create table drs_address (
  address_id   integer      generated by default on null as identity,
  drs_address  varchar2(50)              not null,
  drs_address2 varchar2(50) default null ,
  district     varchar2(20)              not null,
  city_id      integer                   not null,
  postal_code  varchar2(10) default null ,
  phone        varchar2(20)              not null,
  last_update  date                      not null,
  --
  primary key (address_id)
);