prompt - table drs_payment

create table drs_payment (
  payment_id   integer     generated by default on null as identity,
  customer_id  integer                  not null ,
  staff_id     integer                  not null ,
  rental_id    integer     default null          ,
  amount       number(5,2)              not null ,
  payment_date date                     not null ,
  last_update  date                     not null ,
  --
  primary key (payment_id)
);

